# Cloudflare Pages Configuration
name = "stage-transition-maker"
compatibility_date = "2024-01-15"

# Pages build output directory (required for Pages)
pages_build_output_dir = "dist"

# Build configuration
[build]
command = "bun run build"
publish = "dist"