// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnqlybjawvkljhjuqooe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRucWx5Ymphd3ZrbGpoanVxb29lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDc3NTksImV4cCI6MjA2ODk4Mzc1OX0.RlUGYEgjbyKPp5n9vyRzxEUNOYZjrGgco6Tox2juTu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});